### ISSUE TITLE
Segmentation fault (core dumped) running swalo with parameters

### ISSUE THREAD

**Issue by ba1** [atifrahman/SWALO#2]
`~/SWALO/swalo`
displays the help/usage page

`~/SWALO/swalo xx`
Segmentation fault (core dumped)

There was no issue during the building process, though.

**Comment by atifrahman** [comment]
Can you please provide a bit more details? Did you run the steps needed prior to running swalo as mentioned in the readme? Did you provide swalo with the two required parameters?

**Comment by ba1** [comment]
Hey, 
Thanks for the quick reply. Both answers are yes. There was no error for all prior independent steps. Only the last step running the swalo binary causes this error. The error is independent of the input parameters, probably during loading them or running the routines to parse them

**Comment by atifrahman** [comment]
Could you please give me the exact command you're running?

**Comment by atifrahman** [comment]
Also does it print anything before crashing?

**Comment by ba1** [comment]
Nevermind, I found the error. My passed maxInsertSize parameter in prior steps was too small.

**Comment by atifrahman** [comment]
Great!
